// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksbcwdoiinwcjhsfijfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzYmN3ZG9paW53Y2poc2ZpamZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MTUyNDEsImV4cCI6MjA2MTA5MTI0MX0.2fAgGnYSsnCqQOOgId_HhxzwcZQTuAQsVMX1UEhtYzg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);